; Wallboard screens service v1.0.6
; Written by Jan Novotny, 2025 (jan.novotny.cz@gmail.com)
; It uses MS EDGE as default web browser for taking screenshots from websites 
; because of working windows authentication without any problems at all
;
; wallboardScreens (2025) default configuration file
; use ; or # for commenting out unwanted, ignored lines
; empty lines don't take any effect

[service]
service_loop_timeout = 15000
service_thread_timeout = 6000
service_browser_path = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"

[wallboards]
wallboard-bh|--headless --user-data-dir=c:\dev\1 --hide-scrollbars --window-size=1050,980 --default-background-color="00000000" --screenshot="c:\wallboardsTool\wallboard-bh\index.png" https://idnes.cz
wallboard-cc|--headless --user-data-dir=c:\dev\2 --hide-scrollbars --window-size=1050,980 --default-background-color="00000000" --screenshot="c:\wallboardsTool\wallboard-cc\index.png" https://root.cz
wallboard-cc-koordinator|--headless --user-data-dir=c:\dev\3 --hide-scrollbars --window-size=1050,980 --default-background-color="00000000" --screenshot="c:\wallboardsTool\wallboard-cc-koordinator\index.png" https://cnews.cz