[general]
threadCount = 4

[mysql]
server =    127.0.0.1
user =      ...mysql...username...
password =  ...mysql...password...
table =     ...mysql...table...
database =  ...mysql...database...
port =      3306

[net]
listenPort = 9002

[log]
logFile = tariffServer.log
logLevel = error
logType = file
